# Generated by Django 2.1.4 on 2018-12-12 01:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_actividad', models.DateField(blank=True, default=datetime.date.today)),
                ('nivel', models.CharField(max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='detalle_actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.CharField(max_length=20)),
                ('hora_inicio', models.DateField(blank=True, default=datetime.datetime.now)),
                ('hora_fin', models.DateField(blank=True, default=datetime.datetime.now)),
                ('codigo_operacion', models.CharField(max_length=20)),
                ('descripcion_operacion', models.CharField(max_length=20)),
                ('labor_origen', models.CharField(max_length=20)),
                ('labor_destino', models.CharField(max_length=20)),
                ('observaciones', models.CharField(max_length=20)),
                ('tipo_material', models.CharField(max_length=20)),
                ('labor_s', models.CharField(max_length=20)),
                ('proyecto_s', models.CharField(max_length=20)),
                ('fila_s', models.CharField(max_length=20)),
                ('num_taladro_s', models.CharField(max_length=20)),
                ('num_barras_s', models.CharField(max_length=20)),
                ('longitud_s', models.CharField(max_length=20)),
                ('inclinacion_s', models.CharField(max_length=20)),
                ('num_broca_s', models.CharField(max_length=20)),
                ('hr_diesel_inicial', models.CharField(max_length=20)),
                ('hr_diesel_final', models.CharField(max_length=20)),
                ('hr_electricidad_inicial_s', models.CharField(max_length=20)),
                ('hr_electricidad_final_s', models.CharField(max_length=20)),
                ('id_actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividad_detalle_actividad', to='collectorApp.actividad')),
            ],
        ),
        migrations.CreateModel(
            name='equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_equipo', models.CharField(max_length=12)),
                ('modelo', models.CharField(max_length=12)),
                ('estado', models.IntegerField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='operador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_operador', models.CharField(max_length=12)),
                ('usuario', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=12)),
                ('tipo_operador', models.IntegerField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='scoop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horometro', models.CharField(max_length=20)),
                ('numero_cucharas', models.CharField(max_length=20)),
                ('material', models.CharField(max_length=20)),
                ('toneladas', models.CharField(max_length=20)),
                ('id_detalle_actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoop_detalle_actividad', to='collectorApp.detalle_actividad')),
            ],
        ),
        migrations.CreateModel(
            name='simba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percusion', models.CharField(max_length=20)),
                ('longitud', models.CharField(max_length=20)),
                ('id_detalle_actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simba_detalle_actividad', to='collectorApp.detalle_actividad')),
            ],
        ),
        migrations.CreateModel(
            name='turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_turno', models.CharField(max_length=12)),
            ],
        ),
        migrations.AddField(
            model_name='actividad',
            name='id_ayudante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actividad_ayudante', to='collectorApp.operador'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='id_equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividad_equipo', to='collectorApp.equipo'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='id_operador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividad_operador', to='collectorApp.operador'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='id_turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividad_turno', to='collectorApp.turno'),
        ),
    ]
