# Generated by Django 2.1.4 on 2018-12-12 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectorApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='estado',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='operador',
            name='tipo_operador',
            field=models.IntegerField(),
        ),
    ]
