# Generated by Django 2.1.4 on 2018-12-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectorApp', '0002_auto_20181212_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operador',
            name='nombre_operador',
            field=models.CharField(max_length=100),
        ),
    ]
